steps:
  # Install dependencies
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['ci']
    dir: 'frontend'

  # Build the project
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['run', 'build']
    dir: 'frontend'
    env:
      - 'NEXT_PUBLIC_API_URL=https://math-ai-backend-service-dot-$PROJECT_ID.uc.r.appspot.com' # Optional: Pre-fill if known or remove if handled otherwise

  # Deploy to Firebase Hosting (using npx to avoid needing a custom builder image)
  - name: 'node:20'
    entrypoint: 'npx'
    args: ['firebase-tools', 'deploy', '--project', '$PROJECT_ID', '--only', 'hosting']
    dir: 'frontend'

options:
  logging: CLOUD_LOGGING_ONLY
